<%@ Page Language="VB" MasterPageFile="~/SuperAdministrator/shashank.master" Title="Untitled Page" %>

<script runat="server">
    Protected Sub Page_Load(ByVal sender As Object, ByVal e As System.EventArgs)
       
    End Sub

    Protected Sub gridview1_SelectedIndexChanged(ByVal sender As Object, ByVal e As System.EventArgs)
       
        For Each rw As GridViewRow In gridview1.Rows
            If (rw.RowIndex = gridview1.SelectedIndex) Then
                Dim role As String = rw.Cells(1).Text
                
                gridview2.DataSource = Roles.GetUsersInRole(role)
                gridview2.DataBind()
            End If
        Next
    End Sub

    Protected Sub gridview2_RowDeleting(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.GridViewDeleteEventArgs)
        
        For Each row As GridViewRow In gridview2.Rows
            
            If (row.RowIndex = e.RowIndex) Then
                Dim txt As String = row.Cells(1).Text

                Roles.RemoveUserFromRole(txt, gridview1.SelectedRow.Cells(1).Text)
                gridview2.DataSource = Roles.GetUsersInRole(gridview1.SelectedRow.Cells(1).Text)
                gridview2.DataBind()
            End If
        Next
        
        
    End Sub

    Protected Sub gridview1_RowDeleting(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.GridViewDeleteEventArgs)
        Dim index As Integer = e.RowIndex
        
        Dim txt As String = gridview1.Rows(index).Cells(1).Text
        Roles.DeleteRole(txt)
        gridview1.DataSource = Roles.GetAllRoles
        gridview1.DataBind()
        gridview2.DataSource = Roles.GetUsersInRole(gridview1.SelectedRow.Cells(1).Text)
        gridview2.DataBind()
    End Sub

    Protected Sub btnaddrole_Click(ByVal sender As Object, ByVal e As System.EventArgs)
        If (txtaddrole.Text IsNot "") Then
            Roles.CreateRole(txtaddrole.Text)
        End If
        gridview1.DataSource = Roles.GetAllRoles
        gridview1.DataBind()
    End Sub

    Protected Sub Page_PreRender(ByVal sender As Object, ByVal e As System.EventArgs)
        gridview1.DataSource = Roles.GetAllRoles
          
        gridview1.DataBind()
        
    End Sub

    Protected Sub gridview1_PageIndexChanging(ByVal sender As Object, ByVal e As System.Web.UI.WebControls.GridViewPageEventArgs)
        gridview1.PageIndex = e.NewPageIndex
        gridview1.DataBind()
    End Sub
</script>

<asp:Content ID="Content1" ContentPlaceHolderID="superadminhead" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="superadminmaster" Runat="Server">
<div style="position:relative;top:70px;">
<asp:GridView runat="server" ID="gridview1" AutoGenerateSelectButton="true" 
        onselectedindexchanged="gridview1_SelectedIndexChanged" 
        AutoGenerateDeleteButton="true" onrowdeleting="gridview1_RowDeleting" allowpaging="true" PageSize="10"  OnPageIndexChanging="gridview1_PageIndexChanging">
    <Columns>
    
    </Columns>
    </asp:GridView>
    <asp:GridView ID="gridview2" runat="server" autogeneratedeletebutton="true" 
        onrowdeleting="gridview2_RowDeleting"  AllowPaging="true" PageSize="10"></asp:GridView>
<asp:Label ID="Label1" runat="server" Text="create role" ></asp:Label> <asp:TextBox runat="server" ID="txtaddrole"></asp:TextBox>   
   <asp:Button runat="server" ID="btnaddrole" Text="Add role" 
        onclick="btnaddrole_Click" />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
        <br />
</div>
</asp:Content>

